### ISSUE TITLE
US phone numbers not passing validation

### ISSUE THREAD

**Issue by jtmarmon** [victorquinn/chancejs#141]
I'm using chance to build stubs for test cases, and I'm using chance to generate fake user phone numbers. However, I also validate this using [libphonenumber](https://www.npmjs.com/package/libphonenumber) and can't seem to get it to accept any of the numbers generated by `chance.phone({country: 'us'})`. I also tried using [phone](https://www.npmjs.com/package/phone) and that only accepts half of them. Any idea why this would be?

**Comment by jtmarmon** [comment]
To clarify - I use libphonenumber for formatting, but its inability to format a number becomes a validator in a sense

**Comment by oliversalzburg** [comment]
Could you give an example of how you're using libphonenumber and how it fails?

**Comment by jtmarmon** [comment]
`libphonenumber.e164(chance.phone({country: 'us'}), 'US') // Invalid phone number`

`phone` doesn't throw an error, but instead returns an empty array. As I said, this is only in ~50% of cases.  My current workaround is

```javascript
 13 var generatePhone = function() {
 14   var passed = false;
 15   var number;
 16   while (passed === false) {
 17     number = chance.phone({country: 'us'});
 18     try {
 19       libphonenumber.e164(number, 'US');
 20       passed = true;
 21     } catch(e) {
 22     }
 23   }
 24
 25   return number;
 26 };
```

**Comment by oliversalzburg** [comment]
The generated numbers simply aren't in E.164 format. I actually don't see why *any* of them would work.

**Comment by jtmarmon** [comment]
The purpose of `libphonenumber.e164` or `phone` is to _format_ the phone number. If a number passes, that means the libraries consider it a valid phone number.

**Comment by oliversalzburg** [comment]
Oh, I see. I'll look into it if I can find the time, but I would assume that the library is very extensive in the validity checks and would check if the number isn't only syntactically correct, but also has a prefix that is valid for a certain state.

**Comment by jtmarmon** [comment]
Yes I believe that's true. To me it makes sense to have more than just syntactical correctness if the chance already accepts a country code

**Comment by oliversalzburg** [comment]
I looked a bit more into libphonenumber, which, among other things, includes lists like this one: https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/1.txt
It's a list of all valid area prefixes in the US. As you and I already assumed, I guess the generated numbers are checked against that list.

You have a point that generated numbers could (or should) be actually valid numbers. Unless I'm missing something, to achieve that, you would want to include that list to use it to generate numbers.

However, the list is pretty large and including it in the library could bloat it quite a bit. I don't know if small size is favored over correctness for this library or the other way around. Hopefully @victorquinn can shed some light on this.

If #52 is achieved, this would definitely be a great plugin. Until this is resolved, maybe you can use the list I linked above to generate valid numbers in the meanwhile.

**Comment by jtmarmon** [comment]
My workaround works decently at not too much of a performance cost (only goes through like 5 numbers to get a correct one), so I'll stick with that for now. Thanks :)

**Comment by victorquinn** [comment]
Yes, @oliversalzburg as soon as #52 is achieved, I definitely want to pull in that list of valid area codes, but until then I'd prefer to keep the library size down as much as possible. 

Wish there were some formula but unfortunately that isn't the case. Sorry @jtmarmon hopefully we'll solve this in the not-too-distant future!

**Comment by akre54** [comment]
Why would the generated area codes need to be based on real-world numbers? And why stop at area codes? Do we need valid exchange and subscriber numbers too?

Personally I'm happy if I get a number in the form `/[2-9]\d{2}-\d{3}-\d{4}/`

**Comment by jtmarmon** [comment]
@akre54 my use case is that I have automatic validators in my ORM that format and validate phone numbers before saving. without a valid phone number, none of my test data will save.

**Comment by evanjmg** [comment]
+1 also for UK numbers it's breaking
