### ISSUE TITLE
URL Change on Homepage of Chancejs

### ISSUE THREAD

**Issue by nwaomachux** [victorquinn/chancejs#143]
http://www.random.org/integers/? as demonstrated in Advanced section on http://chancejs.com/ should be changed to https://www.random.org/integers/

**Comment by victorquinn** [comment]
Fixed!

Though to be fair, I loaded up the old code snippet and it worked perfectly fine with no issues. However, it is good to add https and I also changed the Chance include to be a hosted version so that script can be run without downloading Chance.

**Comment by nwaomachux** [comment]
Noted.
