### ISSUE TITLE
Build won't install locally (OSX or linux)

### ISSUE THREAD

**Issue by jtmarmon** [victorquinn/chancejs#149]
When I run npm install on any version _above_ `0.6.4` (i.e. 7.x up) I get the following build error
```
chance@0.7.2 postinstall: `lodash compat -o test/lib/lodash/lodash.build.js`

**Comment by victorquinn** [comment]
Hrm, not ideal I will investigate, that has to do with a change merged a few minutes ago.

For now, try `npm install -g lodash` and run it again and it should probably work.

**Comment by kedashoe** [comment]
First post here so let me start by saying thank you for the great library! I am also seeing this issue

    192 error node v0.11.15
    193 error npm  v2.1.6
    194 error code ELIFECYCLE
    195 error chance@0.7.2 postinstall: `lodash compat -o test/lib/lodash/lodash.build.js`
    195 error Exit status 127
    196 error Failed at the chance@0.7.2 postinstall script.
    196 error This is most likely a problem with the chance package,
    196 error not with npm itself.
    196 error Tell the author that this fails on your system:
    196 error     lodash compat -o test/lib/lodash/lodash.build.js

Also, for anyone looking for the quick fix, make sure you get the cli ie `npm install -g lodash-cli`

**Comment by jtmarmon** [comment]
hah that works too. thanks @victorquinn
