### ISSUE TITLE
Is it possible to retrieve somehow the iterator on the chance.n() function?

### ISSUE THREAD

**Issue by falmp** [victorquinn/chancejs#162]
Is it possible to retrieve somehow the iterator value inside the chance.n() callback function?

For example:

```js
chance.n(function() {
      return {
        id: i, // HERE, we currently don't have access to this variable
        name: chance.sentence({words: 2}).slice(0, -1),
        measure: chance.pick([ 'Ampolas', 'Bisnagas', 'Comprimidos', 'Frascos', 'Drageas', 'Blisters', 'Caixas' ]),
        units: chance.natural({ min: 1, max: 1000 })
      }
    }, chance.natural({ min: 1, max: 15 }));
```

I know this may sound strange, but I'm currently generating some random data with auto-increment values.

Thanks!

**Comment by somejeff** [comment]
Instead of referring to ```i```, you could just keep track of your own primary key:

```javascript

var primaryKey = 0;
function createMyThing() {
    return {
        id: primaryKey++, 
        name: chance.sentence({words: 2}).slice(0, -1),
        measure: chance.pick([ 'Ampolas', 'Bisnagas', 'Comprimidos', 'Frascos', 'Drageas', 'Blisters', 'Caixas' ]),
        units: chance.natural({ min: 1, max: 1000 })
    }
}  
                
console.table(chance.n(createMyThing, chance.natural({ min: 1, max: 15 })));
```

If you plan on having a variety of random things constructed, you could have a map of keys:
```javascript

// Stores primary keys by type
var primaryKeyStore = [];
// request the next key for a given type
function nextKey(type) {
   if(!primaryKeyStore[type]) {
       primaryKeyStore[type]=1;
   }
   return primaryKeyStore[type]++;
}

function createMyThing() {
    return {
        id: nextKey("mything"), 
        // ... other properties
    }
}  

function createMyOtherThing() {
    return {
        id: nextKey("myotherthing"), 
        // ... other properties
    }
}  
    
console.table(chance.n(createMyThing, chance.natural({ min: 1, max: 15 })));
console.table(chance.n(createMyOtherThing, chance.natural({ min: 1, max: 15 })));
```

**Comment by victorquinn** [comment]
@falmp I think this is a great idea! 

However, I'm kind of at a loss for how to do this without breaking the existing implementation.

What @somejeff suggests does work, but it's not super elegant. I would prefer to have it passed to the function as an argument (kind of like the [lodash forEach](https://lodash.com/docs#forEach) in which the second argument to the function is the index). But as it's currently written it just passes all parameters on to the calling function so injecting an index in the middle would break the current implementation.

Another hack is as follows, thanks to JavaScript scoping rules:

```js
var chance = require("chance").Chance();

var i = 0;
chance.n(function() {
    return {
        id: i++, // use i here, increment
        name: chance.sentence({words: 2}).slice(0, -1),
        measure: chance.pick([ 'Ampolas', 'Bisnagas', 'Comprimidos', 'Frascos', 'Drageas', 'Blisters', 'Caixas' ]),
        units: chance.natural({ min: 1, max: 1000 })
    }
}, chance.natural({ min: 1, max: 15 }));
```

I'll keep pondering a way to add this more gracefully and update here if I can come up with one!

**Comment by falmp** [comment]
Actually, thinking about it now, the use I was intending for the `n()` function was just a shortcut for a `for`. I'm new to Javascript, so I checked the source code for `n()` and wondered if it was possible to somehow access the internal `i` variable. Nonetheless, I suppose it's not worth breaking the existing implementation to support this, since the `for` or even the suggest approach by @somejeff works just fine. But if somehow you find another approach to expose it, cool. :)

Anyway, thank you you both and keep up the good work.
