### ISSUE TITLE
pick() with count === 1

### ISSUE THREAD

**Issue by leesei** [victorquinn/chancejs#166]
When count parameter is passed to `pick()`, it should return an array.

```js
arr = ['a', 'b', 'c', 'd'];
picked = chance.pick(arr);
// expected 'b'

picked = chance.pick(arr, 1);
// expected [ 'b' ], returns 'b'
```

**Comment by leesei** [comment]
This can be fixed by deleting `|| count === 1` in [LN299](https://github.com/victorquinn/chancejs/blob/develop/bin/chance.js#L299)

I wonder if it is mocha's bug to treat a variable (`'b'`) to have length === 1, see [test](https://github.com/victorquinn/chancejs/blob/develop/test/test.helpers.js#L21-L22)
Is it counting the string length? If so we should amend out test case to include the above test (and assert return is array for other `pick()` tests).

**Comment by victorquinn** [comment]
@leesei I suspect you're right about mocha and a single character having length 1, I should have been more careful in my test!

**Comment by victorquinn** [comment]
Fixed by https://github.com/victorquinn/chancejs/pull/167
