### ISSUE TITLE
extending chance.js

### ISSUE THREAD

**Issue by tkoomzaaskz** [victorquinn/chancejs#178]
Hi,

Is there any way to extend chance.js to provide custom generator functions that would reuse existing generators? Is there any recommended way to do that?

**Comment by victorquinn** [comment]
Hi @tkoomzaaskz !

I added the [Chance mixin functionality](http://chancejs.com/#mixin) for doing exactly this sort of thing. 

This allows you to add new generators to Chance which use the existing ones. For example, let's say you want to add a mixin called `fullemail()` which returns something of the form `Victor Quinn <mail@victorquinn.com>` like many email systems accept. This generator does not exist in Chance at current (thinking about it now, it should!).

You could create a `fullemail()` mixin to Chance easily with the following code:

```js
chance.mixin({
    'fullemail': function() {
        return chance.name() + " <" + chance.email() + ">";
    }
});
```

then from your code you can just call it with `chance.fullemail()` and it will return something like `"Martha Matthews <redked@hom.co.uk>"`

**Comment by tkoomzaaskz** [comment]
Hi Victor! This is exactly what I had in mind. I just didn't see it at the github main page. Thank you!

**Comment by GuyMograbi** [comment]
Why is this awesome feature hidden here in this issue???? 

I had to search for it for a couple of minutes. 

Please add this to your homepage and README. 

This is such a nice library - pretty easy to fall in love with. cool name. 

Having the mixin turns the decision to use this a no-brainer.

**Comment by ducin** [comment]
@GuyMograbi haha :) I think the best what you can do is to extend the README yourself and submit a PR. You're on github, right? ;)
