### ISSUE TITLE
[docs] adding dependent tool: json-schema-faker

### ISSUE THREAD

**Issue by tkoomzaaskz** [victorquinn/chancejs#180]
Hi, I'm a co-author of `json-schema-faker` ([github](https://github.com/pateketrueke/json-schema-faker), [online demo](http://json-schema-faker.js.org)). It's a tool that reads JSON schema and generates fake structures using fake generators. One of the generators is `chance.js`.

We would like to add such information to your README.md. Would you accept a pull request that extends your readme? If so, please tell me how would you like us to do it - I haven't seen any *dependent tools* section in chance.js.

**Comment by victorquinn** [comment]
Yes, I would gladly accept that pull request!

And yes, a *dependent tools* section in the README would be perfect!

**Comment by victorquinn** [comment]
I'd also like to add it to the [main docs site](http://chancejs.com), but you go ahead and add it to the README and I'll add it to the docs site.

**Comment by tkoomzaaskz** [comment]
perfect, thank you... I'm working on it...
