### ISSUE TITLE
Documentation: longitude min/max values should be swapped

### ISSUE THREAD

**Issue by dt-tl** [victorquinn/chancejs#184]
When running the code listed here: http://chancejs.com/#longitude

chance.longitude({min: -77, max: -78});

throws: Uncaught RangeError: Chance: Min cannot be greater than Max.

-77 > -78

**Comment by victorquinn** [comment]
Hi @dt-tl ,

That is the expected behavior because you have set a min that is greater than the max.

`-77` (your min) is greater than `-78` (your max) which is not valid.

You want:

```js
chance.longitude({ min: -78, max: -77 });
```

**Comment by dt-tl** [comment]
Hey victor, I was just pointing out that the official documentation has this issue, and might need to be updated.

**Comment by victorquinn** [comment]
Oooooh my apologies, I didn't catch that, thank you very much!

Updated now.
