### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Xarex** [victorquinn/chancejs#228]
It could just be me... I'm writing a program that utilizes all of chance.js so I've ran all of the functions and these are the ones that did not work:

- Altitude {max} doesn't work
- Country doesn't work
- Currency doesn't work
- CurrencyPairs doesn't work
- SSN doesn't work
- SSN last four digits doesn't work
- Geohash doesn't work
- Color {0x} doesn't work
- URL doesn't work

None of the IDs work:
- Brazilian Tax ID
- Apple Token ID
- Android ID
- BB Pin
- Win7 ANID
- Win8 ANID2

Also: 

- When choosing Age Type: Adult -- 60+ has been known to show up.  
Senior is 60+
Adult should be 18-59(?)

**Comment by oliversalzburg** [comment]
The mobile IDs all work fine for me.

![](https://i.imgur.com/bJBbBii.png)

**Comment by victorquinn** [comment]
Hi @Xarex can you provide some more details such as what kind of system you were running Chance on when you saw this behavior? Was it in node, cli, or in the browser and if browser, which one?

I ask because we have an extensive set of [(passing) tests for all of those generators](https://travis-ci.org/victorquinn/chancejs/jobs/90325461)

Further, I just tried all the ones you claimed didn't work and they all worked just fine for me. Below is a screenshot of some of them:

![screen shot 2016-01-13 at 9 30 09 am](https://cloud.githubusercontent.com/assets/660139/12296856/4a7a4f04-b9d8-11e5-8693-f3a0cbfe97dc.png)

So if they are indeed not working for you, the only thing I can guess is that it has something to do with the system you're running it on or something but it's hard to troubleshoot without more details.

**Comment by Xarex** [comment]
Hey Victor,

Thank you for confirming and looking into it.  It could very well be my end and I will do some more testing.

My website: http://mypost.io/

This is a project I created that allows for anyone to make a webpage or post in minutes.

I'm using advanced custom BBCode ... or a PHP file that gets called and scans the content for [ ] tags and converts them into actual JavaScript code.  The ChanceJS file was beautiful for people who just want to generate random information.  

My code looks like this in the PHP script:

 $bbextended = array(     "/\[randomcountry]/i" => "<.script type=\"text/javascript\".>var randomcountry= chance.integer({ full: true }); document.write(randomcountry);<./script.>", 
  );

(periods added to script to prevent the script tag from rendering)

When someone creates a post and types in [randomcountry], they would get a random country in its place.  

Here is the URL: 
http://mypost.io/post/random-country

Viewing the source, I can see the code:

<.script type="text/javascript".>var randomcountry = chance.country({ full: true }); document.write(randomcountry);<./script.>

So the code is there, but I'm calling it and its not working.

This is present in the header:
//cdnjs.cloudflare.com/ajax/libs/chance/0.5.6/chance.min.js


Here is a working example:
http://mypost.io/post/random-state


Like the PHP script above, this is the code doing the scanning:
    "/\[randomstate]/i" => "<.script type=\"text/javascript\".>var randomstate = chance.state({ territories: true, full: true }); document.write(randomstate);<./script.>",

(periods added to script to prevent the script tag from rendering)

On the random state page, it is working and this is the code:

<.script type="text/javascript".>var randomstate = chance.state({ territories: true, full: true }); document.write(randomstate);<./script.></p>

I hope this gives you some insight into what I'm doing and the URLs might help you see the code for yourself.  It should be working, unless I am missing something.

**Comment by victorquinn** [comment]
Ahhh, ok I see the problem. The version of chance you're loading is very old.

It is version 0.5.6 whereas the latest is 0.8.0 and the docs are written with 0.8.0 in mind.

So it appears you're trying to use things added post 0.5.6 and they're not working.

I'm not sure why cdnjs has such an old, outdated version of Chance and I'm not sure how to tell them to update it, but that would fix your problem.

You could also just use the latest version by downloading it or (this is more dangerous and I probably shouldn't recommend it) you could reference the version of Chance on the docs site directly at `http://chancejs.com/chance.min.js`

**Comment by Xarex** [comment]
And that solved it!  I apologize for any additional work you did Victor!  Yeah, I usually default to cdnjs for everything because I'm already connecting to it for other stuff, so I figured it loads the fastest.. didn't realize the version wasn't fully up to date!  I'll put in a request for them to update your file, but in the meantime, I will the file from the chancejs website.  Thanks again!

**Comment by oliversalzburg** [comment]
Maybe this document is relevant to getting cdnjs to update: https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md
